import os
import platform
import subprocess
import tomllib
from enum import Enum
from pathlib import Path
from types import MappingProxyType
from typing import Any, Self
import globals
from translator import translator

# TODO: Remove "globals" usage here

MAIN_CONFIG_FILENAME: str = "config.toml"

_ = translator.translate

class ConfigLoadResult(Enum):
    SUCCESS = 0
    NOT_FOUND = 1
    ACCESS_DENIED = 2
    CORRUPTED = 3

class ConfigSaveResult(Enum):
    SUCCESS = 0
    FAIL = 1

def get_config_dir_path() -> Path:
    dir_path: Path = Path() / ".config"
    config_dir_name: str = "vrc-avi-scaler"
    if dir_path.exists():
        # mostly for AppImages
        # or if running on an unssupported environment
        return dir_path / config_dir_name
    match os.name:
        case "nt": # Windows
            dir_path = Path("%APPDATA%") / config_dir_name
        case "posix":
            xdg_env = os.environ.get("XDG_CONFIG_HOME")
            if xdg_env:
                dir_path = Path(xdg_env) / config_dir_name
            else:
                dir_path = Path.home() / ".config" / config_dir_name
        case _:
            # unsupported system
            # use the local .config folder
            pass
    return dir_path.resolve()

class Config:
    _open_paths: set[Path] = set()
    def __init__(self, path: Path = get_config_dir_path() / MAIN_CONFIG_FILENAME) -> None:
        path = path.resolve()
        if path in Config._open_paths:
            raise Exception(f"There can only be one config object active on one file. File: {path}")
        Config._open_paths.add(path)
        self._loaded: bool = False
        self._dirty: bool = False
        self._path = path
        self._data: dict[str, Any] = {}
        self._registry: dict[str, Any] = {}

    def __del__(self) -> None:
        Config._open_paths.remove(self._path)

    def get_config_dir_path(self) -> Path:
        return get_config_dir_path()

    @property
    def path(self) -> Path:
        return self._path

    def get_config_path(self) -> Path:
        return self.path

    def show_in_file_explorer(self) -> None:
        path: str = str(self._path)
        match os.name:
            case "nt":
                os.startfile(path) # type:ignore
            case "posix":
                match platform.system().lower():
                    case "darwin": # macOS
                        subprocess.Popen(["open", path])
                    case _:
                        subprocess.Popen(["xdg-open", path])
            case _:
                pass

    def _fix_layout(self, data: Any) -> None:
        # removes duplicate keys generated by tomllib
        to_del = set()
        for key in data:
            if "." in key:
                to_del.add(key)
            value = data[key]
            if isinstance(value, dict):
                self._fix_layout(value)
        for key in to_del:
            del data[key]

    def load(self) -> ConfigLoadResult:
        if self._loaded:
            return ConfigLoadResult.SUCCESS
        path = self._path
        try:
            if not path.exists():
                return ConfigLoadResult.NOT_FOUND
            with path.open('rb') as f:
                try:
                    self._data = tomllib.load(f)
                except:
                    return ConfigLoadResult.CORRUPTED
                self._fix_layout(self._data)
                self._loaded = True
                return ConfigLoadResult.SUCCESS
        except:
            return ConfigLoadResult.ACCESS_DENIED

    def _escape_str(self, text: str) -> str:
        return (text
            .replace('"', '\\"')
            .replace('\n', "\\n")
            .replace('\r', "\\r")
        )

    def save(self) -> ConfigSaveResult:
        if not self._loaded:
            raise Exception("Invalid (save) operation. Not loaded yet.")
        if not self._dirty:
            return ConfigSaveResult.SUCCESS
        try:
            self._path.parent.mkdir(parents=True, exist_ok=True)
            with self._path.open("w") as f:
                title = _("config.title")
                f.write("# " + title + "\n" * 2)
                key_path: list[str] = []
                def write(key_path: list[str], value: Any) -> None:
                    nonlocal f
                    flat_key = ".".join(key_path)
                    translation_key = "config.comment." + flat_key.replace(" ", "_")
                    if translator.has_key(translation_key):
                        comment = _(translation_key)
                        f.write("# " + comment + "\n")
                    if isinstance(value, dict):
                        dict_children = []
                        non_dict_children = []
                        for key in value:
                            value_2 = value[key]
                            if isinstance(value_2, dict):
                                dict_children.append(key)
                            else:
                                non_dict_children.append(key)
                        dict_children.sort()
                        non_dict_children.sort()
                        if non_dict_children:
                            if flat_key:
                                f.write(f'["{flat_key}"]' + "\n")
                            for key in non_dict_children:
                                value_2 = value[key]
                                key_path.append(key)
                                write(key_path, value_2)
                                key_path.pop()
                            f.write("\n")
                        if dict_children:
                            for key in dict_children:
                                value_2 = value[key]
                                key_path.append(key)
                                write(key_path, value_2)
                                key_path.pop()
                    else:
                        key = f'"{self._escape_str(key_path[-1])}"'
                        if isinstance(value, str):
                            value = self._escape_str(value)
                            f.write(f'{key} = "{value}"' + "\n")
                        elif isinstance(value, bool):
                            if value:
                                f.write(f'{key} = true' + "\n")
                            else:
                                f.write(f'{key} = false' + "\n")
                        elif isinstance(value, int) or isinstance(value, float):
                            f.write(f'{key} = {value}' + "\n")
                write([], self._data)
                f.write("\n")
            self._dirty = False
            return ConfigSaveResult.SUCCESS
        except Exception as e:
            print(e)
            return ConfigSaveResult.FAIL

    def _traverse(self, key: str) -> tuple[dict[str, Any], str]:
        key_path = key.split(".")
        data = self._data
        for parent_key in key_path[:-1]:
            data_2 = data.get(parent_key, {})
            data[parent_key] = data_2
            data = data_2
        key = key_path[-1]
        return data, key

    def get(self, key: str) -> Any:
        default = self._registry[key]
        data, key = self._traverse(key)
        value: Any = data.get(key, default)
        if type(value) != type(default):
            return default
        return value

    def set(self, key: str, value: Any) -> None:
        data, key = self._traverse(key)
        if data.get(key) != value:
            self._dirty = True
        data[key] = value

    def register(self, key: str, default: Any) -> Self:
        if not isinstance(default, (bool, int, float, str)):
            raise Exception("Invalid type.")
        self._registry[key] = default
        if self.get(key) == default:
            self.set(key, default)
        return self

    def reset(self, key: str = "") -> None:
        if key:
            self.set(key, self._registry[key])
        else:
            self._loaded = True
            for key in self._registry:
                self.set(key, self._registry[key])

# SHOULD BE REMOVED AT SOME POINT
globals.config = Config()

# DEPRECATED
def reset_config_file() -> None:
    config = globals.config
    config.reset()
    config.save()

# DEPRECATED
def save_config() -> None:
    print(_("config.saving"))
    config = globals.config
    result = config.save()
    if result == ConfigSaveResult.SUCCESS:
        print(_("config.saved"))
    else:
        print(f"Error: {result}")

# DEPRECATED
def read_config() -> ConfigLoadResult:
    config: Config = globals.config
    status = config.load()
    if status != ConfigLoadResult.SUCCESS:
        return status

    globals.FPS = config.get('fps')
    globals.smooth_scaling_step_frequency = globals.FPS * 4.0
    globals.save_config_on_exit = config.get('autosave')

    globals.osc_client_ip = config.get('osc.client.ip')
    globals.osc_client_port = config.get('osc.client.port')
    globals.osc_server_ip = config.get('osc.server.ip')
    globals.osc_server_port = config.get('osc.server.port')
    globals.oscquery_enabled = config.get('oscquery.enable')

    globals.compat_mags = config.get("compat.Mag's Scale Adjuster")
    globals.compat_jackal = config.get("compat.Jackal Scaling System")
    globals.compat_openvrcs = config.get("compat.OpenVRCScaler")

    globals.preferred_locale = config.get("localisation.locale")

    translator.set_locale(globals.preferred_locale)
    if globals.translator and globals.translator != translator:
        globals.translator.set_locale(globals.preferred_locale)

    return ConfigLoadResult.SUCCESS
