[metadata]
Version = 0.2.0

[OSC server]
IP = 127.0.0.1
Port = 9001

[OSC client]
IP = 127.0.0.1
Port = 9000

[limits]
MinHeight = 0.01
MaxHeight = 10000

[compatibility]
; These are compatible third-party scaling systems.
; You can enable/disable them if you want.
; 1: enabled, 0: disabled

; Mag's Scale Adjuster
MagsScaleAdjuster = 1
