[metadata]
Version = 0.1

[OSC server]
IP = 127.0.0.1
Port = 9001

[OSC client]
IP = 127.0.0.1
Port = 9000

[limits]
MinHeight = 0.01
MaxHeight = 10000

[experimental.smoothScaling]
; These are some options for the experimental
; smooth scaling feature (where scaling takes time).

; LengthSeconds is the time (in seconds) it takes to reach the target scale.
LengthSeconds = 10.0

; Play around with this if you see visual flickering.
; Lower values should be better.
StepLengthSeconds = 0.00833333333
